/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stock;

import javax.swing.SwingUtilities;
import java.awt.event.*;
import java.util.Date;
import java.util.Timer;
import java.util.TimerTask;
/**
 *
 * @author Peter
 */
public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
public User player;


    public MainScreen(String s) {
        player = new User(s);
        initComponents();
         Timer timer = new Timer() ;
 TimerTask task = new TimerTask() {
     public void run(){
        Spending.setText(player.getSpending().toString());
        Margin.setText(player.getMargin().toString());
        player.UpdateQueueToOrder();
        player.updateOrders();
        player.UpdatePortfolio();
        player.UpdateSpending();
     
     }
 };
 timer.scheduleAtFixedRate(task,0,10);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        QueueView = new javax.swing.JButton();
        OrderView = new javax.swing.JButton();
        Searches = new javax.swing.JButton();
        Spending = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        Screener = new javax.swing.JButton();
        TRADE = new javax.swing.JButton();
        Margin = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ViewPort = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 23, 460, 290));
        setMaximumSize(new java.awt.Dimension(460, 290));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        QueueView.setText("View Queue");
        QueueView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QueueViewActionPerformed(evt);
            }
        });
        getContentPane().add(QueueView, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        OrderView.setText("View Orders");
        OrderView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderViewActionPerformed(evt);
            }
        });
        getContentPane().add(OrderView, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        Searches.setText("View Searches");
        Searches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchesActionPerformed(evt);
            }
        });
        getContentPane().add(Searches, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, -1, -1));

        Spending.setFont(new java.awt.Font("Adobe Garamond Pro", 1, 48)); // NOI18N
        Spending.setForeground(new java.awt.Color(255, 255, 255));
        Spending.setText("Spending");
        Spending.setText(player.getSpending().toString());
        Spending.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                SpendingPropertyChange(evt);
            }
        });
        getContentPane().add(Spending, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 290, 70));

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        Screener.setText("Screener");
        Screener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScreenerActionPerformed(evt);
            }
        });
        getContentPane().add(Screener, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 120, -1));

        TRADE.setText("TRADE");
        TRADE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TRADEActionPerformed(evt);
            }
        });
        getContentPane().add(TRADE, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 97, -1));

        Margin.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 36)); // NOI18N
        Margin.setForeground(new java.awt.Color(255, 255, 255));
        Margin.setText("Margin");
        Margin.setText(player.getMargin().toString());
        getContentPane().add(Margin, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 150, 60));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stock/background1.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 290));

        ViewPort.setText("View Portfolio");
        ViewPort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewPortActionPerformed(evt);
            }
        });
        getContentPane().add(ViewPort, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 120, -1));

        jLabel5.setFont(new java.awt.Font("Adobe Garamond Pro", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Spending");
        Spending.setText(player.getSpending().toString());
        jLabel5.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel5PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 290, 70));

        jLabel6.setFont(new java.awt.Font("Adobe Garamond Pro", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Spending");
        Spending.setText(player.getSpending().toString());
        jLabel6.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel6PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 290, 70));

        jLabel7.setFont(new java.awt.Font("Adobe Garamond Pro", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Spending");
        Spending.setText(player.getSpending().toString());
        jLabel7.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel7PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 290, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ScreenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScreenerActionPerformed
        // TODO add your handling code here:
        StockScreener.main(player.getName());
    }//GEN-LAST:event_ScreenerActionPerformed

    private void OrderViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderViewActionPerformed

    // TODO add your handling code here:
        DisplayOrders.Display(player.getOrders(), "ORDERS MADE");
        
    }//GEN-LAST:event_OrderViewActionPerformed

    private void TRADEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TRADEActionPerformed
        // TODO add your handling code here:
        Trading.main(player);
    }//GEN-LAST:event_TRADEActionPerformed

    private void QueueViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QueueViewActionPerformed
        // TODO add your handling code here:
          DisplayQ.Display(player.getOrderQueue(), "In Order Queue");

    }//GEN-LAST:event_QueueViewActionPerformed

    private void SearchesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchesActionPerformed
        // TODO add your handling code here:
        player.updateSearches();
        DisplayQ.DisplayS(player.getSearches(), "Searches Made");
    }//GEN-LAST:event_SearchesActionPerformed

    private void SpendingPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_SpendingPropertyChange
        // TODO add your handling code here:
        Spending.setText(player.getSpending().toString());
    }//GEN-LAST:event_SpendingPropertyChange

    private void ViewPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewPortActionPerformed
        // TODO add your handling code here:
        DisplayOrders.DisplayP(player.getPortfolio(), "PORTFOLIO");
    }//GEN-LAST:event_ViewPortActionPerformed

    private void jLabel5PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel5PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5PropertyChange

    private void jLabel6PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel6PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6PropertyChange

    private void jLabel7PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel7PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7PropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen(args[0]).setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Margin;
    private javax.swing.JButton OrderView;
    private javax.swing.JButton QueueView;
    private javax.swing.JButton Screener;
    private javax.swing.JButton Searches;
    private javax.swing.JLabel Spending;
    private javax.swing.JButton TRADE;
    private javax.swing.JButton ViewPort;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration//GEN-END:variables
}
